<?php

/**
 * PluginCatalogueCategoryPropertySetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCatalogueCategoryPropertySetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCatalogueCategoryPropertySetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCatalogueCategoryPropertySet');
    }
}