<?php

/**
 * PluginCatalogueItemPropertyValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCatalogueItemPropertyValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCatalogueItemPropertyValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCatalogueItemPropertyValue');
    }
}