<?php

/**
 * PluginCatalogueCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCatalogueCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCatalogueCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCatalogueCategory');
    }
}