<?php

/**
 * PluginCatalogueCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCatalogueCategory extends BaseCatalogueCategory
{
  public function getIndentedName(){
    return str_repeat('-', $this->getLevel()).' '.$this['name'];
  }
}