<?php

/**
 * PluginCataloguePropertySetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCataloguePropertySetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCataloguePropertySetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCataloguePropertySet');
    }
}