<?php

/**
 * PluginCatalogueCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCatalogueCategoryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginCatalogueCategoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginCatalogueCategory');
  }

  /**
   * Returns tree with hierarchy
   *
   * @return Doctrine_Collection
   */
  public function getTreeHierarchy()
  {
    /** @var Doctrine_Tree_NestedSet $treeObject  */
    $treeObject = $this->getTree();
    $rootColumnName = $treeObject->getAttribute('rootColumnName');

    $rootIds = array();
    $roots = $treeObject->fetchRoots();
    if (count($roots))
    {
      foreach ($roots as $root)
      {
        $rootIds[] = $root->$rootColumnName;
      }
      $tree = $treeObject->fetchTree(array('root_id' => $rootIds));

      return $tree->toHierarchy();
    }
    else
    {
      return null;
    }
  }

  /**
   * Returns query for category selector in Catalogue item edit form
   *
   * @return Doctrine_Query
   */
  public function getItemEditCategoriesQuery()
  {
    $q = $this->createQuery('c');
    $q->orderBy('c.root_id ASC, c.lft ASC');
    if (!sfConfig::get('app_catalogue_add_to_category_with_subcategories', false))
    {
      $q->addWhere('c.rgt = c.lft+1');
    }

    return $q;
  }
}